name: Build Windows EXE

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  build-windows-exe:
    runs-on: windows-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          
      - name: Show project files
        shell: bash
        run: ls -la
        
      - name: Show project files
        shell: bash
        run: ls -la ../../

      - name: Build Windows EXE using jpackage
        shell: powershell
        run: |
          jpackage `
            --type exe `
            --dest dist `
            --name Calculator `
            --app-version 1.0.0 `
            --input ../../build/libs `
            --main-jar Calculator-1.0.0.jar `
            --main-class io.github.ahansantra.calculator.Main `
            --win-console `
            --win-shortcut `
            --win-menu

      - name: Upload EXE
        uses: actions/upload-artifact@v4
        with:
          name: windows-exe
          path: dist/**
          if-no-files-found: error
